[package]
name = "predecessor-item-cleaner"
version = "0.1.0"
edition = "2021"

[dependencies]
nanoid = "0.4.0"
rand = "0.8.5"
regex = "1.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
